# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-23 01:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belt_review_app', '0002_auto_20170423_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='belt_review_app.User'),
        ),
    ]
